services:
    app:
        image: main:1.0
        container_name: main_app
        restart: always
        build:
            context: .
        command: /bin/sh /shared/entry.sh
        user: "${UID}:${GID}"
        volumes:
            - ./code:/app/code
            - ./storage:/app/storage
            - ./config:/app/config:ro
            - .:/shared
        depends_on:
            - psql
            - redis
            - search
        networks:
            - ai_network
        ports:
            - "5000:5000"

    redis:
        image: redis:7.2.4-alpine3.19
        container_name: ai_redis
        restart: always
        command: ["redis-server", "/docker/redis/redis.conf"]
        deploy:
            resources:
                limits:
                    memory: 512M
        volumes:
            - redis-data:/data
            - ./docker/redis/redis.conf:/docker/redis/redis.conf
        logging:
            driver: none
        networks:
            - ai_network
    psql:
        image: postgres:16-alpine
        restart: always
        container_name: ai_psql
        environment:
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: ai_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./storage/db/pgdata:/var/lib/postgresql/data
            - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - ai_network
        
    nginx:
        image: nginx:1.25-alpine
        container_name: ai_nginx
        ports:
            - "${PORT}:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./storage:/app/storage:ro
        depends_on:
            - app
        logging:
            driver: none
        networks:
            - ai_network

    search:
        container_name: ai-search
        image: getmeili/meilisearch:v1.1
        restart: always
        networks:
            - ai_network
        logging:
            driver: none
        volumes:
            - ./storage/ai_search:/meili_data

volumes:
    redis-data:
        driver: local

    ai_search:
        driver: local



networks:
    ai_network:
        name: ai
